export const prefix = 'LIST_'
export const LIST_LOADING = prefix + 'LOADING'
export const LIST_REQUEST_LIST = prefix + 'REQUEST_LIST'
export const LIST_SET_LIST = prefix + 'SET_LIST'
export const LIST_SET_CALC_LIST = prefix + 'SET_CALC_LIST'
export const LIST_SET_SUMMARY = prefix + 'SET_SUMMARY'
export const LIST_SET_ERROR = prefix + 'SET_ERROR'