export const prefix = 'LOGIN_'
export const LOGIN_LOADING = prefix + 'LOADING'
export const LOGIN_CHANGE_USERID = prefix + 'CHANGE_USERID'
export const LOGIN_CHANGE_PASSWORD = prefix + 'CHANGE_PASSWORD'
export const LOGIN_REQUEST_LOGIN_REQUEST = prefix + 'REQUEST_LOGIN_REQUEST'
export const LOGIN_REQUEST_LOGIN_RESULT = prefix + 'REQUEST_LOGIN_RESULT'
export const LOGIN_SET_ERROR = prefix + 'SET_ERROR'