export const prefix = 'LOGIN_'
export const LOGIN_LOADING = prefix + 'LOADING'
export const LOGIN_CHANGE_USER = prefix + 'CHANGE_USER'
export const LOGIN_CHANGE_PASSWORD = prefix + 'CHANGE_PASSWORD'
export const LOGIN_REQUEST_LOGIN_REQUEST = prefix + 'REQUEST_LOGIN_REQUEST'
export const LOGIN_REQUEST_LOGIN_RESULT = prefix + 'REQUEST_LOGIN_RESULT'