export const prefix = 'SETTING_'
export const SETTING_LOADING = prefix + 'LOADING'
export const SETTING_CHANGE_USERNAME = prefix + 'CHANGE_USERNAME'
export const SETTING_REQUEST_CHANGE_USERNAME = prefix + 'REQUEST_CHANGE_USERNAME'
export const SETTING_SET_ERROR = prefix + 'SET_ERROR'